### ISSUE TITLE
Support for latest Modernzir

### ISSUE THREAD

**Issue by mrac** [zalando/dress-code#141]
Dresscode depend on outdated Modernizr 2.8.3. Let's update for ver.3.x.x.

In meanwhile we could add to README how to install the old modernizr. It can be done via:
```npm install --save npm-modernizr@2.8.3```

**Comment by rbarilani** [comment]
+1 Yep we should...

**Comment by rbarilani** [comment]
@xonic apparently the "simple touch" support was removed from modernizer in the latest 3.x version.
see https://modernizr.com/news/modernizr-3-new-release-site. We should investigate more on this...

**Comment by rbarilani** [comment]
@gabrielhl @xonic @mrac what about removing the "touch" / "no-touch" special behaviors, why?

 * We are not using it to hide or showing element but just for hover and active: http://www.prowebdesign.ro/how-to-deal-with-hover-on-touch-screen-devices/

* we are relying on a parent selector and it requires some javascript to be present on a page (Modernizer or some simple script like):```if (!("ontouchstart" in document.documentElement)) {
document.documentElement.className += " no-touch";
}```

* In the latest version of Modernizer the feature detection was removed because there is not reliable way to recognize a touch device.

* It makes our code more complex and more difficult to reuse with mixins/include or extend approach see: https://github.com/zalando/dress-code/blob/develop/src/styles/atoms/_btn.scss.


WDYT?

**Comment by gabrielhl** [comment]
No issue from my side, I would be OK with removing the reliance on the touch/no-touch.

**Comment by xonic** [comment]
I think the issue with hover and active is that active will never show on touch devices because hover is shown instead. If you look at the btn scss you can see that all we're doing is removing hover styles from touch screens. Let's test what happens if we remove it. If UX is not totally compromised I'm fine with removing. I think this is something @gabrielhl and I should take care of.

**Comment by gabrielhl** [comment]
Also Modernizr 3.x is not available in CDN, so we'd need to change that. Either it should be loaded by the demo or include as a dependency in the SC install.

**Comment by gabrielhl** [comment]
I've started working on this today with @xonic, will push a preliminary version soon.

**Comment by rbarilani** [comment]
@gabrielhl Actually I want to remove that dependency.... maybe we can still use it but just in the demo.

**Comment by gregdeane** [comment]
@gabrielhl @xonic Any movement on this? Thanks!

**Comment by xonic** [comment]
Oh sorry, we forgot to reply our decision. From UX perspective it’s fine to remove it. Thanks
