### ISSUE TITLE
dc-html & dc-body: try to get rid of complexity regarding fonts, line height...

### ISSUE THREAD

**Issue by dami-gg** [zalando/dress-code#165]

**Comment by gabrielhl** [comment]
@dami-gg @xonic can you add a better description so other people can work on this? as it is no one can really contribute to this topic.

**Comment by dami-gg** [comment]
I have no clue right now what this was about, @xonic do you?

**Comment by rbarilani** [comment]
@dami-gg This it's tough!

All the font-sizes line-height are based on rem.
So you need to add ```dc-html``` and ```dc-body``` to have all the components looks properly. (```dc-html```se the base font-size and the base line-height then also ```dc-body``` set a line-height).

This is recognized as a painful point when you wanna integrate dress-code in existing apps that are using different units since adding mandatory dc-html will screw up existing components.

For more infos and ideas how to solve this "challenge"... as always ... feel free to approach me.

**Comment by xonic** [comment]
I think some of us should sit together and discuss the issue. As @rbarilani said, it's a tough one and we should align before changing this.

**Comment by rbarilani** [comment]
@xonic maybe one idea can be exposing the possibiliy at least via sass to customize the unit by using a $variable and then a mixin for unit something like:

```
dc-defautl-unit: 'px'

.dc-component {
   padding: dc-unit(1.2) // this mixin output 12px or 1.2 rem based on the value of dc-defautl-unit
}
```

So if you have a pixels based app you can still using pixels..... @dami-gg @sambhav-gore WDYT?

**Comment by frontendherodk** [comment]
I discussed this with @rbarilani, @sambhav-gore and @gabrielhl 

We will leave it as is for now. If you choose to use dress code these are the terms. 
You can always override this defaults in your own styles if it doesn't fit your setup.
