### ISSUE TITLE
First table cell's padding mobile view

### ISSUE THREAD

**Issue by lorabv** [zalando/dress-code#380]
First table cell's padding is not correct on mobile which leads to it's content not being displayed correctly:

![localhost-3000- iphone 6](https://user-images.githubusercontent.com/3195013/30536071-bfbce1da-9c64-11e7-9d8a-1aa010963e46.png)

The reason is the style added for .dc-table__td:first-child:
![screen shot 2017-09-18 at 11 32 03](https://user-images.githubusercontent.com/3195013/30536157-07a69f68-9c65-11e7-8c85-8dae9935af40.png)

**Comment by dami-gg** [comment]
This seems to be a local problem of the User Management application since it's overriding the value of the padding-left of dc-table__td for the first child.

Please always check the possible issues also in the [Dress Code demo](http://zalando.github.io/dress-code). In this case, you can see that the padding-left is different:

![image](https://user-images.githubusercontent.com/3198244/30635130-c556206e-9df1-11e7-954f-bc9b57caecee.png)

Could you @lorabv please check in the User Management application and let us know whether I'm correct with the assumptions and we can close this ticket? Thanks!

**Comment by lorabv** [comment]
You are right @dami-gg , it was a problem in the User Management application. We didn't have the .dc-table--responsive class added to the table. Thank you for referring me to the Dress Code demo, it helped to find the problem quickly!
