### ISSUE TITLE
react support

### ISSUE THREAD

**Issue by fogfish** [zalando/dress-code#404]
I know that your library do not have any "pre-defined" atoms and molecules for react. Have you heard about any extension that helps to utilise you library with react?

**Comment by fogfish** [comment]
damn... bad luck... even the issue number says `404 Not Found`.

**Comment by dami-gg** [comment]
I'm not totally sure I got what you mean but Dress Code has been designed to be a generic solution. It doesn't enforce any framework but should work right away with any React codebase.

Could you please be more descriptive with your problem?

**Comment by fogfish** [comment]
Let me elaborate my question with an example of dialog

```
<div class="dc-dialog">
   <div class="dc-dialog__content">
      <div class="dc-dialog__body">
         <div class="dc-dialog__close">
	    <i class="dc-icon dc-icon--close dc-icon--interactive dc-dialog__close__icon"></i>
         </div>
        <h3 class="dc-dialog__title">This is a dialog</h3>
        <h4 class="dc-dialog__subtitle">Subtitle or step</h4>
           <p>This is the content area. Content goes here. Actions (buttons, most of the times) should go in the bottom part.</p>
      </div>
      <div class="dc-dialog__actions">
         <a href="#" class="dc-link dc-dialog__actions__link">Action</a>
	    <button class="dc-btn dc-btn--primary">Action</button>
	  </div>
   </div>
</div>
```

There are not challenge to use it along with react. You are absolutely right it just work. However, I'd like to express this dialog using React.Components. If there an easy way to make it instead of writing these components by yourself.

```
export const Body = ({title, subtitle, children}) => (
   <div class="dc-dialog__body">
      <h3 class="dc-dialog__title">{title}</h3>
      <h4 class="dc-dialog__subtitle">{subtitle}</h4>
      {children}
   </div>
)

export const Dialog = ({children}) => (
   <div class="dc-dialog">
      <div class="dc-dialog__content">
         {children}
      </div>
   </div>
)

...
```

**Comment by dami-gg** [comment]
I get your point but as said, Dress Code is not intended to be tied to any framework in particular but a set of elements to be used via CSS classes in any HTML markup.

Perhaps in the future, we might consider creating another library with Dress Code components for React but, as per design, will never be provided in this manner by the Dress Code library itself.

In fact, we had some users requesting something similar in the past for AngularJS instead, when it was the most popular framework at that time, and we discarded it for the same reason. Time has proven us to be right in our decision since as you can see now other frameworks are more popular and still the generic design approach of Dress Code can be used with them.

I hope my answer clarifies it. ;) Thanks for your feedback anyway!

**Comment by fogfish** [comment]
Thank you for clarification!

**Comment by fogfish** [comment]
Guys! I've kicked out the react wrapper of your library. So far, I've procedure with few atoms/molecules that needed for my immediate use-cases. However, I am planning to continue with other elements.

Feedback, comments and contribution is welcome!
https://github.com/fogfish/react-dress-code

**Comment by rbarilani** [comment]
@fogfish That's awesome!

**Comment by dami-gg** [comment]
cool. I'm looking forward to seeing what comes out of that!
